complexity:
  TooManyFunctions:
    active: false
  LongParameterList:
    active: false

style:
  ClassOrdering:
    active: true
  MandatoryBracesLoops:
    active: true
  UseEmptyCounterpart:
    active: true
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 150
  WildcardImport:
    active: false

performance:
  ArrayPrimitive:
    active: true

naming:
  PackageNaming:
    active: false
